"""Build the small static detail pages from the shared portfolio shell."""
from pathlib import Path
import re

root = Path(__file__).parent / 'dist'
shell = (root / 'index.html').read_text()
pages = {
    'me': ('A little about me', '''<img class="portrait" src="/assets/portrait.jpg" alt="My portrait" width="124" height="124"><h1>A curious human, behind the screen.</h1><p>I like the place where ideas become things you can actually use. The quiet details. The playful interactions. The satisfaction of getting something just right.</p><p>This little space brings those things together — a few projects, a few experiments, and a tiny version of me keeping you company.</p><p class="case-note">Personal introduction draft — ready for your story.</p><section class="detail-section"><h2>side quests these days</h2><div class="side-quests"><span>⌨ Making little things</span><span>✎ Exploring motion</span><span>☕ One more cup</span></div></section><section class="detail-section"><h2>experience.</h2><p class="case-note">Your experience, roles, and dates will live here.</p></section><section class="detail-section"><h2>education.</h2><p class="case-note">Your education and learning journey will live here.</p></section><section class="detail-section"><h2>Let’s make something thoughtful.</h2><a class="pill" href="/contact/">say hello</a></section>'''),
    'contact': ('Say hello', '''<span class="section-label">a conversation starts somewhere</span><h1>Let’s make something good.</h1><p>A project, a possibility, or just a hello — there’s always room for a good conversation.</p><div class="contact-note"><p>Contact details are being added.</p><p class="case-note">This portfolio preview is waiting for your email and social links.</p></div>'''),
}
cases = [
    ('document-workspace', 'A calmer workspace for complex documents', 'An exploration of helping people review information without losing its context.', 'Document workspace', [('Supplier quotation.pdf', 'Ready to review'), ('Purchase order.pdf', 'Verified'), ('Invoice.pdf', 'Needs attention')], 'Information is only useful when people can understand where it came from and what to do with it.', 'Keep the source and its structured information together. Use clear processing states, a readable hierarchy, and a deliberate review step before moving forward.', 'The next step would be to test whether someone can find a document, verify its information, and confidently complete a review.'),
    ('developer-portal', 'Making developer tools feel human', 'A concept for a clearer path from discovering a service to getting started.', 'Developer workspace', [('Discover services', '01'), ('Configure application', '02'), ('Review and connect', '03')], 'A tool can be technically powerful and still leave people wondering what to do next.', 'Group related services, explain dependencies where decisions happen, and make the next step visible throughout setup.', 'A useful test would ask someone to choose the right service and finish setup without needing outside help.'),
    ('form-builder', 'Small building blocks, endless possibilities', 'A form-building concept that makes configuration feel approachable.', 'Form workspace', [('Project name', 'Short text'), ('Target date', 'Date'), ('Progress', 'Selection')], 'People who know what information they need should be able to shape how it is collected.', 'Use familiar field types, sensible defaults, and a preview that shows the result while someone is building.', 'The next step would be to observe someone creating and checking a form, especially when fields depend on each other.'),
]
for slug, title, intro, preview, rows, problem, solution, reflection in cases:
    row_html = ''.join(f'<div class="preview-row"><span>{a}</span><span>{b}</span></div>' for a,b in rows)
    pages['work/' + slug] = (title, f'''<span class="section-label">sample case study · concept</span><h1>{title}</h1><p>{intro}</p><p class="case-note">Illustrative portfolio content. This is not a claim of client work or measured results.</p><dl class="details-grid"><div><dt>Project type</dt><dd>Product design concept</dd></div><div><dt>Focus</dt><dd>Clarity & interaction</dd></div></dl><section class="detail-section"><h2>Solution preview</h2><a class="back-link" href="#solution">jump to solution ↓</a><div class="concept-preview"><div class="preview-bar"><strong>{preview}</strong><span>Concept preview</span></div>{row_html}</div></section><section class="detail-section"><span class="section-label">the starting point</span><h2>The challenge</h2><p>{problem}</p></section><section class="detail-section" id="solution"><span class="section-label">a considered response</span><h2>The design direction</h2><p>{solution}</p></section><section class="detail-section"><span class="section-label">what comes next</span><h2>Test the useful thing.</h2><p>{reflection}</p></section>''')
for path, (title, body) in pages.items():
    page = shell.replace('<body>', '<body class="detail">')
    page = re.sub(r'<title>.*?</title>', f'<title>{title} — Portfolio</title>', page)
    page = re.sub(r'<main id="content" tabindex="-1">.*?</main>', '<main id="content" tabindex="-1">' + body + '<a class="back-link" href="/">← back to work</a></main>', page, flags=re.S)
    destination = root / path / 'index.html'
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(page)
print(f'Generated {len(pages)} detail pages.')
